part of '../student_management.ui.dart';

class StudentFormScreen extends StatefulWidget {
  final String institutionId;
  final StudentEntity? studentEntity;

  const StudentFormScreen({
    super.key,
    required this.institutionId,
    this.studentEntity,
  });

  @override
  State<StudentFormScreen> createState() => _StudentFormScreenState();
}

class _StudentFormScreenState extends State<StudentFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _studentIdController = TextEditingController();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  String? _selectedClassId;
  List<ClassEntity> _classes = [];
  bool _isLoading = false;
  bool _isLoadingClasses = true;

  bool get isEditing => widget.studentEntity != null;

  @override
  void initState() {
    super.initState();
    _loadClasses();
    if (widget.studentEntity != null) {
      _studentIdController.text = widget.studentEntity!.studentId;
      _nameController.text = widget.studentEntity!.name;
      _selectedClassId = widget.studentEntity!.classId;
      _emailController.text = widget.studentEntity!.email ?? '';
      _phoneController.text = widget.studentEntity!.phone ?? '';
    }
  }

  @override
  void dispose() {
    _studentIdController.dispose();
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    super.dispose();
  }

  Future<void> _loadClasses() async {
    // We need to get classes for the dropdown
    // Use the class management bloc or directly use the use case
    // For simplicity, we'll inject GetClassesUseCase via context or create a new bloc
    // Actually, let's use the ClassManagementBloc from context
    if (!mounted) return;

    setState(() {
      _isLoadingClasses = true;
    });

    try {
      final classManagementBloc = context.read<ClassManagementBloc>();
      classManagementBloc.add(LoadClasses(institutionId: widget.institutionId));

      // Wait for the bloc to emit the classes
      await classManagementBloc.stream.firstWhere(
        (state) => state is ClassesLoaded || state is ClassManagementError,
      );

      if (!mounted) return;

      final state = classManagementBloc.state;
      if (state is ClassesLoaded) {
        setState(() {
          _classes = state.classes;
          _isLoadingClasses = false;
        });
      } else if (state is ClassManagementError) {
        setState(() {
          _isLoadingClasses = false;
        });
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to load classes: ${state.message}'),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLoadingClasses = false;
        });
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to load classes: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedClassId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a class'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    if (isEditing) {
      context.read<StudentManagementBloc>().add(
            UpdateStudent(
              institutionId: widget.institutionId,
              studentId: widget.studentEntity!.studentId, // studentId cannot change
              name: _nameController.text.trim(),
              classId: _selectedClassId!,
              email: _emailController.text.trim().isEmpty
                  ? null
                  : _emailController.text.trim(),
              phone: _phoneController.text.trim().isEmpty
                  ? null
                  : _phoneController.text.trim(),
            ),
          );
    } else {
      context.read<StudentManagementBloc>().add(
            CreateStudent(
              institutionId: widget.institutionId,
              studentId: null, // Auto-generated by data source
              name: _nameController.text.trim(),
              classId: _selectedClassId!,
              email: _emailController.text.trim().isEmpty
                  ? null
                  : _emailController.text.trim(),
              phone: _phoneController.text.trim().isEmpty
                  ? null
                  : _phoneController.text.trim(),
            ),
          );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(isEditing ? 'Edit Student' : 'Create Student'),
        backgroundColor: Colors.red,
        foregroundColor: Colors.white,
      ),
      body: BlocListener<StudentManagementBloc, StudentManagementState>(
        listener: (context, state) {
          if (state is StudentOperationSuccess) {
            setState(() {
              _isLoading = false;
            });
            Navigator.pop(context, true);
          } else if (state is StudentManagementError) {
            setState(() {
              _isLoading = false;
            });
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(state.message),
                backgroundColor: Colors.red,
              ),
            );
          }
        },
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  isEditing
                      ? 'Update student details'
                      : 'Enter student details',
                  style: theme.textTheme.titleLarge,
                ),
                const SizedBox(height: 24),
                if (isEditing) ...[
                  TextFormField(
                    controller: _studentIdController,
                    decoration: const InputDecoration(
                      labelText: 'Student ID',
                      hintText: 'Student ID',
                      prefixIcon: Icon(Icons.badge),
                      border: OutlineInputBorder(),
                    ),
                    enabled: false, // Read-only in edit mode
                    readOnly: true,
                  ),
                  const SizedBox(height: 16),
                ],
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    labelText: 'Full Name',
                    hintText: 'Enter student name',
                    prefixIcon: Icon(Icons.person),
                    border: OutlineInputBorder(),
                  ),
                  enabled: !_isLoading && !_isLoadingClasses,
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Name is required';
                    }
                    if (value.trim().length < 2) {
                      return 'Name must be at least 2 characters';
                    }
                    return null;
                  },
                  textCapitalization: TextCapitalization.words,
                ),
                const SizedBox(height: 16),
                if (_isLoadingClasses)
                  const Padding(
                    padding: EdgeInsets.all(16.0),
                    child: Center(child: CircularProgressIndicator()),
                  )
                else
                  CustomDropdownButtonFormField<String>(
                    value: _selectedClassId,
                    decoration: const InputDecoration(
                      labelText: 'Class',
                      hintText: 'Select a class',
                      prefixIcon: Icon(Icons.class_),
                      border: OutlineInputBorder(),
                    ),
                    items: _classes.map((classEntity) {
                      return DropdownMenuItem<String>(
                        value: classEntity.id,
                        child: Text(classEntity.name),
                      );
                    }).toList(),
                    onChanged: _isLoading || _isLoadingClasses
                        ? null
                        : (value) {
                            setState(() {
                              _selectedClassId = value;
                            });
                          },
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please select a class';
                      }
                      return null;
                    },
                  ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _emailController,
                  decoration: const InputDecoration(
                    labelText: 'Email (Optional)',
                    hintText: 'Enter email address',
                    prefixIcon: Icon(Icons.email),
                    border: OutlineInputBorder(),
                  ),
                  enabled: !_isLoading && !_isLoadingClasses,
                  keyboardType: TextInputType.emailAddress,
                  validator: (value) {
                    if (value != null && value.trim().isNotEmpty) {
                      final emailRegex = RegExp(
                        r'^[^@]+@[^@]+\.[^@]+',
                      );
                      if (!emailRegex.hasMatch(value.trim())) {
                        return 'Please enter a valid email address';
                      }
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _phoneController,
                  decoration: const InputDecoration(
                    labelText: 'Phone (Optional)',
                    hintText: 'Enter phone number',
                    prefixIcon: Icon(Icons.phone),
                    border: OutlineInputBorder(),
                  ),
                  enabled: !_isLoading && !_isLoadingClasses,
                  keyboardType: TextInputType.phone,
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed:
                      (_isLoading || _isLoadingClasses) ? null : _handleSubmit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.red,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor:
                                AlwaysStoppedAnimation<Color>(Colors.white),
                          ),
                        )
                      : Text(isEditing ? 'Update Student' : 'Create Student'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

