// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHImzC7tVH0RcmEsiEmaJTqf04cDoHoeE',
    appId: '1:586528260468:web:a37210a0ceb7538e9b2c21',
    messagingSenderId: '586528260468',
    projectId: 'schattendancepproject',
    authDomain: 'schattendancepproject.firebaseapp.com',
    storageBucket: 'schattendancepproject.firebasestorage.app',
    measurementId: 'G-D3W86516ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZY5kOLc3Ce8UqKLrAMgcZGA1L755qdE',
    appId: '1:586528260468:android:f635b0f3688448979b2c21',
    messagingSenderId: '586528260468',
    projectId: 'schattendancepproject',
    storageBucket: 'schattendancepproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFUm6nR_BC0wnGbsrZZAJ7tJpH63Qo7as',
    appId: '1:586528260468:ios:dc5c04af7a74c9029b2c21',
    messagingSenderId: '586528260468',
    projectId: 'schattendancepproject',
    storageBucket: 'schattendancepproject.firebasestorage.app',
    iosBundleId: 'com.example.taskMasterTot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFUm6nR_BC0wnGbsrZZAJ7tJpH63Qo7as',
    appId: '1:586528260468:ios:dc5c04af7a74c9029b2c21',
    messagingSenderId: '586528260468',
    projectId: 'schattendancepproject',
    storageBucket: 'schattendancepproject.firebasestorage.app',
    iosBundleId: 'com.example.taskMasterTot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHImzC7tVH0RcmEsiEmaJTqf04cDoHoeE',
    appId: '1:586528260468:web:8b8c760ec905c29c9b2c21',
    messagingSenderId: '586528260468',
    projectId: 'schattendancepproject',
    authDomain: 'schattendancepproject.firebaseapp.com',
    storageBucket: 'schattendancepproject.firebasestorage.app',
    measurementId: 'G-BERNHHEJB6',
  );
}
