import 'package:presento/imports.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:presento/modules/auth/domain/domain.dart';
import 'package:presento/ui/auth/auth.ui.dart' hide InstitutionsLoaded;
import 'package:presento/ui/dashboard/screens/dashboard_router.dart';
import 'package:presento/ui/user_management/user_management.ui.dart';
import 'package:presento/ui/institution_management/institution_management.ui.dart';
import 'package:presento/ui/class_management/class_management.ui.dart';
import 'package:presento/ui/student_management/student_management.ui.dart';
import 'package:presento/ui/attendance_management/attendance_management.ui.dart';
import 'package:presento/core/di/injection_container.dart' as di;

part 'error/exceptions.dart';
part 'error/failures.dart';
part 'network/network_info.dart';
part 'routing/app_router.dart';
part 'routing/route_guards.dart';
part 'services/firebase_service.dart';
part 'utils/constants.dart';
part 'utils/validators.dart';
part 'utils/extensions.dart';
part 'utils/user_role.dart';
part 'repositories/base_repository.dart';
part 'repositories/repositories.dart';
part 'datasources/firebase_base_data_source.dart';
